services:
    db:
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=shadyman6
            - POSTGRES_DB=planner
        ports:
            - '5432:5432'
        networks:
            - base_name_network

    app:
        build: .
        environment:
            - DATABASE_URL=postgresql://postgres:shadyman6@db:5432/planner
            - JWT_SECRET=AHAHAHAHAHAH
        depends_on:
            - db
        networks:
            - base_name_network
        ports:
            - '4200:4200'

networks:
    base_name_network:
        driver: bridge
